version: '3.9'

services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    environment:
      - MINIO_ROOT_USER=your_access_key
      - MINIO_ROOT_PASSWORD=your_secret_key
      - MINIO_BROWSER_REDIRECT_PORT=9000
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          memory: 512M

  uploader:
    build: ./uploader
    container_name: uploader
    depends_on:
      - minio
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=your_access_key
      - MINIO_SECRET_KEY=your_secret_key

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m  # Ограничение размера хранилища